name: Build Electron App for macOS

on:
  push:
    tags:
      - 'v*' # 在推送版本标签时触发，例如 v1.0.0 #如何发布新的版本APP,存在了release 标签,然后需要删除release 标签,再重新发布
  pull_request:
    branches: [main]
  workflow_dispatch: # 允许手动触发
# 添加权限配置
permissions:
  contents: write
  packages: write
jobs:
  build-macos:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: npm install
        run: |
          npm install


      - uses: nick-fields/retry@v2
        name: Build Electron app for macOS
        with:
          timeout_minutes: 30
          max_attempts: 2
          #command: npm run build:mac
          command: npm run build:mac:universal
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            dist/*.dmg
            dist/*.zip
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

